/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AttentionsRouteImport } from './routes/attentions'
import { Route as AutomationsRouteImport } from './routes/automations'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as InferenceRouteImport } from './routes/inference'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as LocalInferenceRouteImport } from './routes/local-inference'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as MeshRouteImport } from './routes/mesh'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as ThemesRouteImport } from './routes/themes'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as ApiEventsRouteImport } from './routes/api.events'
import { Route as ChatSessionIdRouteImport } from './routes/chat.$sessionId'
import { Route as ApiArtifactsArtifactIdRouteImport } from './routes/api.artifacts.$artifactId'
import { Route as ApiKnowledgeBundleIdRouteImport } from './routes/api.knowledge.$bundleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttentionsRoute = AttentionsRouteImport.update({
  id: '/attentions',
  path: '/attentions',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsRoute = AutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const InferenceRoute = InferenceRouteImport.update({
  id: '/inference',
  path: '/inference',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalInferenceRoute = LocalInferenceRouteImport.update({
  id: '/local-inference',
  path: '/local-inference',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const MeshRoute = MeshRouteImport.update({
  id: '/mesh',
  path: '/mesh',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemesRoute = ThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatSessionIdRoute = ChatSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => ChatRoute,
} as any)
const ApiArtifactsArtifactIdRoute = ApiArtifactsArtifactIdRouteImport.update({
  id: '/api/artifacts/$artifactId',
  path: '/api/artifacts/$artifactId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKnowledgeBundleIdRoute = ApiKnowledgeBundleIdRouteImport.update({
  id: '/api/knowledge/$bundleId',
  path: '/api/knowledge/$bundleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attentions': typeof AttentionsRoute
  '/automations': typeof AutomationsRoute
  '/chat': typeof ChatRouteWithChildren
  '/console': typeof ConsoleRoute
  '/inference': typeof InferenceRoute
  '/knowledge': typeof KnowledgeRoute
  '/local-inference': typeof LocalInferenceRoute
  '/memory': typeof MemoryRoute
  '/mesh': typeof MeshRoute
  '/notifications': typeof NotificationsRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/skills': typeof SkillsRoute
  '/tasks': typeof TasksRoute
  '/themes': typeof ThemesRoute
  '/usage': typeof UsageRoute
  '/api/events': typeof ApiEventsRoute
  '/chat/$sessionId': typeof ChatSessionIdRoute
  '/api/artifacts/$artifactId': typeof ApiArtifactsArtifactIdRoute
  '/api/knowledge/$bundleId': typeof ApiKnowledgeBundleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attentions': typeof AttentionsRoute
  '/automations': typeof AutomationsRoute
  '/chat': typeof ChatRouteWithChildren
  '/console': typeof ConsoleRoute
  '/inference': typeof InferenceRoute
  '/knowledge': typeof KnowledgeRoute
  '/local-inference': typeof LocalInferenceRoute
  '/memory': typeof MemoryRoute
  '/mesh': typeof MeshRoute
  '/notifications': typeof NotificationsRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/skills': typeof SkillsRoute
  '/tasks': typeof TasksRoute
  '/themes': typeof ThemesRoute
  '/usage': typeof UsageRoute
  '/api/events': typeof ApiEventsRoute
  '/chat/$sessionId': typeof ChatSessionIdRoute
  '/api/artifacts/$artifactId': typeof ApiArtifactsArtifactIdRoute
  '/api/knowledge/$bundleId': typeof ApiKnowledgeBundleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attentions': typeof AttentionsRoute
  '/automations': typeof AutomationsRoute
  '/chat': typeof ChatRouteWithChildren
  '/console': typeof ConsoleRoute
  '/inference': typeof InferenceRoute
  '/knowledge': typeof KnowledgeRoute
  '/local-inference': typeof LocalInferenceRoute
  '/memory': typeof MemoryRoute
  '/mesh': typeof MeshRoute
  '/notifications': typeof NotificationsRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/skills': typeof SkillsRoute
  '/tasks': typeof TasksRoute
  '/themes': typeof ThemesRoute
  '/usage': typeof UsageRoute
  '/api/events': typeof ApiEventsRoute
  '/chat/$sessionId': typeof ChatSessionIdRoute
  '/api/artifacts/$artifactId': typeof ApiArtifactsArtifactIdRoute
  '/api/knowledge/$bundleId': typeof ApiKnowledgeBundleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attentions'
    | '/automations'
    | '/chat'
    | '/console'
    | '/inference'
    | '/knowledge'
    | '/local-inference'
    | '/memory'
    | '/mesh'
    | '/notifications'
    | '/sessions'
    | '/settings'
    | '/setup'
    | '/skills'
    | '/tasks'
    | '/themes'
    | '/usage'
    | '/api/events'
    | '/chat/$sessionId'
    | '/api/artifacts/$artifactId'
    | '/api/knowledge/$bundleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attentions'
    | '/automations'
    | '/chat'
    | '/console'
    | '/inference'
    | '/knowledge'
    | '/local-inference'
    | '/memory'
    | '/mesh'
    | '/notifications'
    | '/sessions'
    | '/settings'
    | '/setup'
    | '/skills'
    | '/tasks'
    | '/themes'
    | '/usage'
    | '/api/events'
    | '/chat/$sessionId'
    | '/api/artifacts/$artifactId'
    | '/api/knowledge/$bundleId'
  id:
    | '__root__'
    | '/'
    | '/attentions'
    | '/automations'
    | '/chat'
    | '/console'
    | '/inference'
    | '/knowledge'
    | '/local-inference'
    | '/memory'
    | '/mesh'
    | '/notifications'
    | '/sessions'
    | '/settings'
    | '/setup'
    | '/skills'
    | '/tasks'
    | '/themes'
    | '/usage'
    | '/api/events'
    | '/chat/$sessionId'
    | '/api/artifacts/$artifactId'
    | '/api/knowledge/$bundleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttentionsRoute: typeof AttentionsRoute
  AutomationsRoute: typeof AutomationsRoute
  ChatRoute: typeof ChatRouteWithChildren
  ConsoleRoute: typeof ConsoleRoute
  InferenceRoute: typeof InferenceRoute
  KnowledgeRoute: typeof KnowledgeRoute
  LocalInferenceRoute: typeof LocalInferenceRoute
  MemoryRoute: typeof MemoryRoute
  MeshRoute: typeof MeshRoute
  NotificationsRoute: typeof NotificationsRoute
  SessionsRoute: typeof SessionsRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  SkillsRoute: typeof SkillsRoute
  TasksRoute: typeof TasksRoute
  ThemesRoute: typeof ThemesRoute
  UsageRoute: typeof UsageRoute
  ApiEventsRoute: typeof ApiEventsRoute
  ApiArtifactsArtifactIdRoute: typeof ApiArtifactsArtifactIdRoute
  ApiKnowledgeBundleIdRoute: typeof ApiKnowledgeBundleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attentions': {
      id: '/attentions'
      path: '/attentions'
      fullPath: '/attentions'
      preLoaderRoute: typeof AttentionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations': {
      id: '/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inference': {
      id: '/inference'
      path: '/inference'
      fullPath: '/inference'
      preLoaderRoute: typeof InferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local-inference': {
      id: '/local-inference'
      path: '/local-inference'
      fullPath: '/local-inference'
      preLoaderRoute: typeof LocalInferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mesh': {
      id: '/mesh'
      path: '/mesh'
      fullPath: '/mesh'
      preLoaderRoute: typeof MeshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/themes': {
      id: '/themes'
      path: '/themes'
      fullPath: '/themes'
      preLoaderRoute: typeof ThemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$sessionId': {
      id: '/chat/$sessionId'
      path: '/$sessionId'
      fullPath: '/chat/$sessionId'
      preLoaderRoute: typeof ChatSessionIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/api/artifacts/$artifactId': {
      id: '/api/artifacts/$artifactId'
      path: '/api/artifacts/$artifactId'
      fullPath: '/api/artifacts/$artifactId'
      preLoaderRoute: typeof ApiArtifactsArtifactIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/knowledge/$bundleId': {
      id: '/api/knowledge/$bundleId'
      path: '/api/knowledge/$bundleId'
      fullPath: '/api/knowledge/$bundleId'
      preLoaderRoute: typeof ApiKnowledgeBundleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ChatRouteChildren {
  ChatSessionIdRoute: typeof ChatSessionIdRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatSessionIdRoute: ChatSessionIdRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttentionsRoute: AttentionsRoute,
  AutomationsRoute: AutomationsRoute,
  ChatRoute: ChatRouteWithChildren,
  ConsoleRoute: ConsoleRoute,
  InferenceRoute: InferenceRoute,
  KnowledgeRoute: KnowledgeRoute,
  LocalInferenceRoute: LocalInferenceRoute,
  MemoryRoute: MemoryRoute,
  MeshRoute: MeshRoute,
  NotificationsRoute: NotificationsRoute,
  SessionsRoute: SessionsRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  SkillsRoute: SkillsRoute,
  TasksRoute: TasksRoute,
  ThemesRoute: ThemesRoute,
  UsageRoute: UsageRoute,
  ApiEventsRoute: ApiEventsRoute,
  ApiArtifactsArtifactIdRoute: ApiArtifactsArtifactIdRoute,
  ApiKnowledgeBundleIdRoute: ApiKnowledgeBundleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
