/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as ThemesRouteImport } from './routes/themes'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatSessionIdRouteImport } from './routes/chat.$sessionId'
import { Route as ApiEventsRouteImport } from './routes/api.events'

const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemesRoute = ThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatSessionIdRoute = ChatSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => ChatRoute,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteWithChildren
  '/memory': typeof MemoryRoute
  '/notifications': typeof NotificationsRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/skills': typeof SkillsRoute
  '/themes': typeof ThemesRoute
  '/usage': typeof UsageRoute
  '/api/events': typeof ApiEventsRoute
  '/chat/$sessionId': typeof ChatSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteWithChildren
  '/memory': typeof MemoryRoute
  '/notifications': typeof NotificationsRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/skills': typeof SkillsRoute
  '/themes': typeof ThemesRoute
  '/usage': typeof UsageRoute
  '/api/events': typeof ApiEventsRoute
  '/chat/$sessionId': typeof ChatSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteWithChildren
  '/memory': typeof MemoryRoute
  '/notifications': typeof NotificationsRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/skills': typeof SkillsRoute
  '/themes': typeof ThemesRoute
  '/usage': typeof UsageRoute
  '/api/events': typeof ApiEventsRoute
  '/chat/$sessionId': typeof ChatSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/memory'
    | '/notifications'
    | '/sessions'
    | '/settings'
    | '/setup'
    | '/skills'
    | '/themes'
    | '/usage'
    | '/api/events'
    | '/chat/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/memory'
    | '/notifications'
    | '/sessions'
    | '/settings'
    | '/setup'
    | '/skills'
    | '/themes'
    | '/usage'
    | '/api/events'
    | '/chat/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/memory'
    | '/notifications'
    | '/sessions'
    | '/settings'
    | '/setup'
    | '/skills'
    | '/themes'
    | '/usage'
    | '/api/events'
    | '/chat/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRouteWithChildren
  MemoryRoute: typeof MemoryRoute
  NotificationsRoute: typeof NotificationsRoute
  SessionsRoute: typeof SessionsRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  SkillsRoute: typeof SkillsRoute
  ThemesRoute: typeof ThemesRoute
  UsageRoute: typeof UsageRoute
  ApiEventsRoute: typeof ApiEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/themes': {
      id: '/themes'
      path: '/themes'
      fullPath: '/themes'
      preLoaderRoute: typeof ThemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$sessionId': {
      id: '/chat/$sessionId'
      path: '/$sessionId'
      fullPath: '/chat/$sessionId'
      preLoaderRoute: typeof ChatSessionIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ChatRouteChildren {
  ChatSessionIdRoute: typeof ChatSessionIdRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatSessionIdRoute: ChatSessionIdRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRouteWithChildren,
  MemoryRoute: MemoryRoute,
  NotificationsRoute: NotificationsRoute,
  SessionsRoute: SessionsRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  SkillsRoute: SkillsRoute,
  ThemesRoute: ThemesRoute,
  UsageRoute: UsageRoute,
  ApiEventsRoute: ApiEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
